name: flutter_word_dictation
description: A cross-platform word dictation app built with Flutter, based on the original Python wordDictation tool.
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI and Material Design
  material_color_utilities: ^0.11.1
  
  # State Management
  provider: ^6.1.1
  
  # Database
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  
  # File Operations
  file_picker: ^8.0.0+1
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # Document Processing
  archive: ^3.4.9
  xml: ^6.4.2
  excel: ^4.0.3
  
  # Image Processing
  image: ^4.1.30
  
  # Utilities
  uuid: ^4.2.1
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  
  # Platform Integration
  url_launcher: ^6.2.2
  package_info_plus: ^4.2.0
  
  # Logging
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^3.0.1
  
  # Testing
  mockito: ^5.4.4
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  # fonts:
  #   - family: CustomIcons
  #     fonts:
  #       - asset: assets/fonts/custom_icons.ttf